plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md

title: Intuiting Machine
description: A machine knowing or understanding something because of a 'feeling' rather than because of facts or what someone has told.
